# Generated by Django 2.1.2 on 2019-10-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_top', models.BooleanField(default=True)),
                ('developer', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_shot', to='top_app.App')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='top_app.App')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('app', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='screenshot',
            unique_together={('app', 'url')},
        ),
    ]
